Create main.yml
snyk-labs/snyk-repo-diff pull request #19
Opened 2022-07-05 20:20 UTC by kevin-s31

Creating this yaml to generate jira issues from github issues

2022-07-05 20:30 UTC, scotte-snyk requested changes

2022-07-05 20:30 UTC, scotte-snyk commented on .github/workflows/main.yml
> +          jiraHost: ${{ secrets.JIRA_HOST }}
CSENG_JIRA_HOST

2022-07-05 20:30 UTC, scotte-snyk commented on .github/workflows/main.yml
> +          jiraUsername: ${{ secrets.JIRA_USERNAME }}
CSENG_JIRA_USERNAME

2022-07-05 20:30 UTC, scotte-snyk commented on .github/workflows/main.yml
> +          jiraPassword: ${{ secrets.JIRA_PASSWORD }}
CSENG_JIRA_PASSWORD

2022-07-06 12:57 UTC, kevin-s31 reviewed
Modified the variable names

2022-07-06 13:18 UTC, merged